apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-volume
  namspace: default
  label: 
    deploymentConfig: "docker-registry"
spec:
  capacity:
    storage: 15Gi
  accessModes: 
  - ReadWriteOnce
  nfs:
    path: /exports/registry
    server: nfs.test-openshift.com
  PersistentVolumeClaimPolicy: Recycle
  claimRef:
    name: claim1
    namespace: default
