kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: registry-pvclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: glusterfs-registry-block
