apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /exports/registry
    server: infra.test-openshift.com
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    name: registry-pvclaim
    namespace: default
