apiVersion: v1
kind: PersistentVolume
metadata:
  name: logging-volume
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /exports/logging
    server: infra.test-openshift.com
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: openshift-logging
    name: logging-es-0
